[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 921600
test_framework = unity

lib_deps =
    adafruit/Adafruit MCP23017 Arduino Library
    https://github.com/espressif/esp32-camera.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/jeevan9s/device-libs.git

    Servo
    Wifi
    Wire

lib_ignore = ADS131M04/examples

test_build_src = true

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -I include
    -I test

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

build_src_filter = +<*> -<../libdeps/device-libs/ADS131M04/examples/*>